name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main # Specifica il branch che attiverà il deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.13" # Usa la versione di Node.js compatibile con Angular

      - name: Install dependencies
        run: npm install # Questo comando installerà le dipendenze definite in package.json

      - name: Build Angular app
        run: npx ng build --configuration production --base-href="/Todo-app-frontend/" # Usa npx per eseguire Angular CLI

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }} # Usa il token predefinito
          publish_dir: ./dist/frontend # Assicurati che il percorso della cartella di output sia corretto
          publish_branch: gh-pages # Specifica il branch di pubblicazione
